server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;


    location /api/ {
      proxy_pass http://backend:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    # All routes fall back to index.html
    # This is what makes React Router work after a page refresh
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets aggressively
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Don't cache index.html so users always get the latest version
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
